sudo: required
services:
  - docker

before_install:
  - docker build -t dockerfestina/react-test -f ./client/Dockerfile.dev ./client
  
script:  
  - docker run dockerfestina/react-test npm test --  --coverage

after_success:
  - docker build -t dockerfestina/multi-client ./client
  - docker build -t dockerfestina/multi-nginx ./nginx
  - docker build -t dockerfestina/multi-server ./server
  - docker build -t dockerfestina/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dockerfestina/multi-client
  - docker push dockerfestina/multi-nginx
  - docker push dockerfestina/multi-server
  - docker push dockerfestina/multi-worker